# 接続情報を直接指定（リレーさせない）
spring.datasource.url=jdbc:postgresql://tetris_id_user:uVal22WyRef90TxeFzDRYKSIL6k7L4cQ@dpg-d6ieg4juibrs73abmvl0-a/tetris_id
spring.datasource.username=tetris_id_user
spring.datasource.password=uVal22WyRef90TxeFzDRYKSIL6k7L4cQ
spring.datasource.driver-class-name=org.postgresql.Driver

# テーブルを自動作成する設定
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# バージョンによって必要になる場合があるため追加
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect