# 直接URLとユーザー情報を書き込む
spring.datasource.url=jdbc:postgresql://tetris_id_user:uVal22WyRef90TxeFzDRYKSIL6k7L4cQ@dpg-d6ieg4juibrs73abmvl0-a/tetris_id
spring.datasource.username=tetris_id_user
spring.datasource.password=uVal22WyRef90TxeFzDRYKSIL6k7L4cQ
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernateの自動設定（テーブル作成）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true